name: CI

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      herbie-db:
        image: postgres:12.1
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: herbie_test_db
        ports:
        - 8888:5432
    steps:

    - name: Checkout working branch
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Cache requirements
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-testing.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-testing.txt
        python setup.py bdist_wheel

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest --verbose
#      env:
#        DATABASE_URL: postgres://user:password@localhost:5432/herbie_db
#        SECRET_KEY: thisisasecret
#        PUBSUB_EMULATOR_HOST: localhost:8085
#        GCLOUD_PUBSUB_PROJECT_ID: herbie-app